// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void test1() {
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(562, 740));
    driver.findElement(By.name("q")).click();
    driver.findElement(By.cssSelector(".sbhl .wM6W7d > span")).click();
    driver.findElement(By.cssSelector(".MjjYud:nth-child(2) .LC20lb")).click();
    js.executeScript("window.scrollTo(0,200)");
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".fr-dib:nth-child(1)")).click();
    vars.put("win605", waitForWindow(2000));
    driver.switchTo().window(vars.get("win605").toString());
    driver.findElement(By.linkText("Веб-разработка")).click();
    js.executeScript("window.scrollTo(0,400)");
    driver.findElement(By.linkText("Backend-разработка")).click();
  }
}
